version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 16...
      - sudo apt update
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - nvm install node
      - sudo apt install npm
      - npm install
  pre_build:
    commands:
      # echo Installing dependencies...
      - npm
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build