version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 16...
      - apt update
      - apt install npm
      - npm install
  pre_build:
    commands:
      # echo Installing dependencies....
      - npm
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build